

#######
# SITE SETTINGS
#
# title appears in the header
title: The MegaLands project
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon:
# description, keywords, and image for meta tags
description: "MegaLands investigates the human-environmental drivers of megalithic societies in Northwestern Iberia (5th–2nd millennium BCE), integrating spatial analysis, radiocarbon dating, and palaeoenvironmental data."
keywords: "Prehistory, Environmental Archaeology, Megalithic sites"
featured-image: "/images/pedra_arca.jpg"
# add search box to footer? true/false
search: true

# author settings for cc-by, appears in the footer and credits
author: Miguel Carrero & Noemí Silva

# year or date published
pub_year: 2026
# location of code, the full url to your github repository
source-code: https://github.com/megalandsUSC/megalandsUSC.github.io
github_username: megalandsUSC
# Funding information
funding: PID2024-156264NA-I00 funded by MICIU / AEI / 10.13039/501100011033 / FEDER, EU.

##########
# URL VARIABLES [optional!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
#
# use url for the domain, e.g. https://megalandsusc.github.io
# on gh-pages follow the pattern: https://username.github.io
url: https://megalandsUSC.github.io
# use baseurl to add subsection of the domain, e.g. /megalands
# on gh-pages this is a / followed by the name of the repository
# For user/organization main sites (username.github.io), baseurl is empty: ""
baseurl: ""


##########
# GOOGLE ANALYTICS [optional!]
#
# leave this blank or comment out to NOT include google code
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
google-analytics-id:

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
