/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WorkPackagesRouteImport } from './routes/work-packages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPackagesRoute = WorkPackagesRouteImport.update({
  id: '/work-packages',
  path: '/work-packages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/outreach': typeof OutreachRoute
  '/publications': typeof PublicationsRoute
  '/social-media': typeof SocialMediaRoute
  '/team': typeof TeamRoute
  '/work-packages': typeof WorkPackagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/outreach': typeof OutreachRoute
  '/publications': typeof PublicationsRoute
  '/social-media': typeof SocialMediaRoute
  '/team': typeof TeamRoute
  '/work-packages': typeof WorkPackagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/outreach': typeof OutreachRoute
  '/publications': typeof PublicationsRoute
  '/social-media': typeof SocialMediaRoute
  '/team': typeof TeamRoute
  '/work-packages': typeof WorkPackagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/methodology'
    | '/outreach'
    | '/publications'
    | '/social-media'
    | '/team'
    | '/work-packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/methodology'
    | '/outreach'
    | '/publications'
    | '/social-media'
    | '/team'
    | '/work-packages'
  id:
    | '__root__'
    | '/'
    | '/methodology'
    | '/outreach'
    | '/publications'
    | '/social-media'
    | '/team'
    | '/work-packages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodologyRoute: typeof MethodologyRoute
  OutreachRoute: typeof OutreachRoute
  PublicationsRoute: typeof PublicationsRoute
  SocialMediaRoute: typeof SocialMediaRoute
  TeamRoute: typeof TeamRoute
  WorkPackagesRoute: typeof WorkPackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-packages': {
      id: '/work-packages'
      path: '/work-packages'
      fullPath: '/work-packages'
      preLoaderRoute: typeof WorkPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodologyRoute: MethodologyRoute,
  OutreachRoute: OutreachRoute,
  PublicationsRoute: PublicationsRoute,
  SocialMediaRoute: SocialMediaRoute,
  TeamRoute: TeamRoute,
  WorkPackagesRoute: WorkPackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
